### PR TITLE
Add admin page markup, close#16

### PR DESCRIPTION
**Pull request by Lenkelheit**
# Description

Added admin page markup

#### Fixes # (issues)
#16 
#### Opens # (issues)
#42 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] My code builds clean without any errors or warnings

## Design

If you have change design fill in this part

### A picture of design after pull request
image

### CODE REVIEW

**Comment by iamprovidence** [comment]
there is no need in **Cancel** button

**Comment by Lenkelheit** [comment]
> there is no need in **Cancel** button

why?

**Comment by iamprovidence** [comment]
> > there is no need in **Cancel** button
> 
> why?

when will you use it?

**Comment by Lenkelheit** [comment]
> > > there is no need in **Cancel** button
> > 
> > 
> > why?
> 
> when will you use it?

to reset all cells

**Comment by iamprovidence** [comment]
> > > > there is no need in **Cancel** button
> > > 
> > > 
> > > why?
> > 
> > 
> > when will you use it?
> 
> to reset all cells

it could be done after submit button is pressed. but ok, you can merge

**Comment by Lenkelheit** [comment]
> > > > > there is no need in **Cancel** button
> > > > 
> > > > 
> > > > why?
> > > 
> > > 
> > > when will you use it?
> > 
> > 
> > to reset all cells
> 
> it could be done after submit button is pressed. but ok, you can merge

all this is made by sketches

**Pull request merged**
